version: 2.1

orbs:
  macos: circleci/macos@2.0.1
  win: circleci/windows@4.1
  android: circleci/android@2.0.3

commands:
  install-macos-bazel:
    steps:
      - run:
          name: "Install Bazel"
          command: |
            set -ex
            curl -OL "https://github.com/bazelbuild/bazel/releases/download/4.2.1/bazel-4.2.1-installer-darwin-x86_64.sh"
            shasum -c -a 256 tools/bazel-4.2.1-installer-darwin-x86_64.sh.sha256
            sh ./bazel-4.2.1-installer-darwin-x86_64.sh

  install-linux-bazel:
    steps:
      - run:
          name: "Install Bazel"
          command: |
            set -ex
            curl -OL "https://github.com/bazelbuild/bazel/releases/download/4.2.1/bazel_4.2.1-linux-x86_64.deb"
            shasum -c -a 256 tools/bazel_4.2.1-linux-x86_64.deb.sha256
            sudo dpkg -i bazel_4.2.1-linux-x86_64.deb

  install-win-bazel:
    steps:
      - run:
          name: "Install Bazel"
          command: |
            choco install bazel --version=4.2.1

  build-swift-macos:
    steps:
      - run: make build-swift-macos

  build-swift-ios:
    steps:
      - run: make build-swift-ios

  build-and-test-c:
    steps:
      - run: make build-c
      - run: make test-c

jobs:
  lint-swift:
    macos:
      xcode: 14.0.0
    steps:
      - checkout
      - run: brew install swift-format
      - run: swift-format --version
      - run: make lint-swift

  build-and-test-macos:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - install-macos-bazel
      - build-and-test-c
      - build-swift-macos

  build-and-test-ios:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - install-macos-bazel
      - build-and-test-c
      - build-swift-ios

  build-and-test-android:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      - install-linux-bazel
      - build-and-test-c

  build-and-test-win:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - install-win-bazel
      - run:
          name: "Build TsMuxer"
          command: bazel build //tsmuxer:tsmuxer
      - run:
          name: "Test TsMuxer"
          command: bazel test --test_output=all --test_timeout=700 //tsmuxer/tests:tsmuxer_tests

workflows:
  lint:
    jobs:
      - lint-swift

  build-and-test:
    jobs:
      - build-and-test-macos
      - build-and-test-android
      - build-and-test-win
      - build-and-test-ios
