version: 2.1

orbs:
  macos: circleci/macos@2.0.1
  win: circleci/windows@4.1

commands:
  install-cmake-macos:
    steps:
      - run:
          name: "Install CMake"
          command: |
            set -ex
            brew install cmake

  install-cmake-linux:
    steps:
      - run:
          name: "Install CMake"
          command: |
            set -ex
            wget https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.sh -q -O /tmp/cmake-install.sh
            chmod u+x /tmp/cmake-install.sh
            sudo mkdir -p /usr/local/bin/cmake
            sudo /tmp/cmake-install.sh --skip-license --prefix=/usr/local/bin/cmake
            rm /tmp/cmake-install.sh
            echo 'export PATH=/usr/local/bin/cmake/bin:$PATH' >> "$BASH_ENV"
            source "$BASH_ENV"
            cmake --version

  install-cmake-win:
    steps:
      - run:
          name: "Install CMake"
          command: |
            set -ex
            choco install cmake -y
            echo 'export PATH=/c/Program\ Files/CMake/bin:$PATH' >> "$BASH_ENV"
            source "$BASH_ENV"
            cmake --version

  build-swift-macos:
    steps:
      - run: make build-swift-macos

  build-swift-ios:
    steps:
      - run: make build-swift-ios

  build-and-test-c-xcode:
    steps:
      - run: |
          cmake --preset xcode
          cmake --build --clean-first --preset xcode-release
          ctest --preset xcode-release

  build-and-test-c-linux:
    steps:
      - run: |
          cmake --preset default
          cmake --build --clean-first --preset default
          ctest --preset default

  build-and-test-c-win:
    steps:
      - run: |
          cmake --preset vs-x64
          cmake --build --clean-first --preset vs-x64-release
          ctest --preset vs-x64
jobs:
  build-and-test-macos:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - install-cmake-macos
      - build-and-test-c-xcode
      - build-swift-macos

  build-and-test-ios:
    macos:
      xcode: 13.3.1
    steps:
      - checkout
      - install-cmake-macos
      - build-and-test-c-xcode
      - build-swift-ios

  build-and-test-linux:
    machine:
      image: ubuntu-2204:2022.10.2
    resource_class: small
    steps:
      - checkout
      - install-cmake-linux
      - build-and-test-c-linux

  build-and-test-win:
    executor:
      name: win/server-2022
      shell: bash.exe
      size: medium
    steps:
      - checkout
      - install-cmake-win
      - build-and-test-c-win

workflows:
  build-and-test:
    jobs:
      - build-and-test-macos
      - build-and-test-linux
      - build-and-test-win
      - build-and-test-ios
